language: node_js
node_js:
  - "6.9.1"	
 
install:
  - npm install
 
script:
  - hexo g
 
after_script:
  - cd ./public
  - git init
  - git config user.name "springhack"
  - git config user.email "springhack@live.cn"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${CO_USER}:${CO_PASS}@${CO_REPO}" master:master
 
env:
 global:
   - CO_REPO: git.coding.net/springhack/SpringHack-Blog.git
